version: "3.9"

services:
  pedidos-postgres:
    image: postgres:15
    container_name: pedidos-postgres
    environment:
      POSTGRES_USER: pedidos_user
      POSTGRES_PASSWORD: pedidos_password
      POSTGRES_DB: pedidos_db
    ports:
      - "5432:5432"


  pedidos-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pedidos-backend
    environment:
       - ConnectionStrings__Postgres=Host=pedidos-postgres;Database=pedidos_db;Username=pedidos_user;Password=pedidos_password
    depends_on:
      - rabbitmq
      - pedidos-postgres
    ports:
      - 8080:8080
      - 8081:8081

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq